package qtriptest.pages;
import java.util.UUID;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.pagefactory.AjaxElementLocatorFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
public class RegisterPage {
    static RemoteWebDriver driver;
    @FindBy(name = "email")
    private static WebElement emailTextBox;
    @FindBy(name = "password")
    private static WebElement passwordTextBox;
    @FindBy(name = "confirmpassword")
    private static WebElement confirmPasswordTextBox;
    @FindBy(xpath = "//a[text()='Register']")
    private static WebElement registerButton;
    @FindBy(xpath = "//*[@id='registerForm']")
    private WebElement registerFormLayout;
    // @BeforeTest()
    // public static void createDriver() throws MalformedURLException {
    //     driver = DriverSingleton.getInstanceOfSingletonBrowserClass().getDriver();
    //     new HomePage(driver);
    //     new RegisterPage(driver);
    //     new LoginPage(driver);
    // }
    public RegisterPage(RemoteWebDriver driver) {
        RegisterPage.driver=driver;
        // PageFactory.initElements(driver, this);
        PageFactory.initElements(new AjaxElementLocatorFactory(driver, 20), this);
    }
    public boolean checkRegisterPageNavigation() {
        WebDriverWait wait = new WebDriverWait(driver, 5);
        return wait.until(ExpectedConditions.visibilityOf(registerFormLayout)).isDisplayed();
    }
    public static void registerANewUser(String email, String password, String confirmpassword, boolean isUserAutoGenerated) {
        String newEmail;
        if (isUserAutoGenerated) {
            // Append a unique identifier (UUID) to the provided email
            newEmail = email + UUID.randomUUID();
        } else {
            // Use the provided email as-is
            newEmail = email;
        }
        emailTextBox.sendKeys(newEmail);
        passwordTextBox.sendKeys(password);
        confirmPasswordTextBox.sendKeys(password);
        registerButton.click();
    }
}
